package edu.brown.cs32.message;

// NOTE: THIS WILL NEED TO BE UPDATED AS WE IMPLEMENT MORE FEATURES
public enum MessageType {
  NEW_CLIENT_NO_CODE,
  NEW_CLIENT_WITH_CODE,
  UPDATE_LEADERBOARD,
  SEND_ORBS,
  REMOVE_ORB,
  UPDATE_POSITION,
  UPDATE_SCORE,
  YOU_DIED,
  OTHER_USER_DIED,
  SET_GAME_CODE,
  ERROR,
  SUCCESS,
  JOIN_ERROR,
  JOIN_SUCCESS
}
