package edu.brown.cs32.message;

// NOTE: THIS WILL NEED TO BE UPDATED AS WE IMPLEMENT MORE FEATURES
public enum MessageType {
  NEW_CLIENT, CLIENT_LEFT, GET_LEADERBOARD, UPDATE_SCORE, ERROR, SUCCESS
}
