package edu.brown.cs32.message;

// NOTE: THIS WILL NEED TO BE UPDATED AS WE IMPLEMENT MORE FEATURES
public enum MessageType {
  NEW_CLIENT, GET_LEADERBOARD, UPDATE_SCORE, USER_DIED, ERROR, SUCCESS
}
